---
settings:
  name: StorageGRID solutions and sesources
  search: storagegrid-enable,storagegrid,storagegrid-appliances
  internal:
    pdf_enabled: true
    termcheck_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-cn,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-tw
sidebar:
  entries:
  - title: StorageGRID解决方案和资源
    url: "/index.html"
  - title: 试用StorageGRID
    url: "/evaluation-software.html"
  - section: third-party
  - section: product-feature-guides
  - section: tools-apps-guides
  - section: examples
  - section: technical-reports
  - title: 试用StorageGRID
    url: "/evaluation-software.html"
  - title: 博客文章
    url: "/blogs.html"
  - title: StorageGRID 文档
    url: "/storagegrid-documentation.html"
  - title: 法律声明
    url: "/legal-notices.html"
