---
permalink: technical-reports/monitor/index.html 
sidebar: sidebar 
keywords: monitoring, storagegrid 
summary: 深入了解NetApp StorageGRID、其错误条件以及如何使用Splunk等外部应用程序有效监控它。 
---
= StorageGRID监控简介
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../../media/


[role="lead"]
了解如何使用外部应用程序(例如Splunk)监控StorageGRID系统。

通过有效监控NetApp StorageGRID基于对象的存储、管理员可以快速响应紧急问题、并主动添加资源来处理不断增长的工作负载。本报告提供了有关如何监控关键指标以及如何利用外部监控应用程序的一般性指导。本文档旨在补充现有的"监控和故障排除"指南。

NetApp StorageGRID部署通常由多个站点和多个节点组成、这些站点和节点用于创建分布式容错对象存储系统。在StorageGRID等分布式弹性存储系统中、出现错误情况是正常的、而网格仍正常运行。作为管理员、您面临的挑战是、了解错误条件(例如节点关闭)出现问题时应立即解决的阈值、以及应分析的信息。通过分析StorageGRID提供的数据、您可以了解自己的工作负载并做出明智的决策、例如何时添加更多资源。

StorageGRID提供了深入探讨监控主题的出色文档。本报告假设您熟悉StorageGRID、并且已阅读有关它的文档。我们不会重复这些信息、而是参阅本指南中的产品文档。StorageGRID产品文档以PDF格式在线提供。

本文档旨在对产品文档进行补充、并讨论如何使用外部应用程序(例如Splunk)监控StorageGRID系统。



== 数据源

要成功监控NetApp StorageGRID、请务必了解从何处收集有关StorageGRID系统运行状况和操作的数据。

* *Web UI和信息板。*StorageGRID网格管理器提供了一个顶级视图、可显示管理员在逻辑演示文稿中需要查看的信息。作为管理员、您还可以深入了解服务级别信息、以便进行故障排除和收集日志。
* *审核日志。*StorageGRID会保留有关放置、获取和删除等租户操作的精细审核日志。您还可以跟踪对象从数据管理规则的加热到应用的整个生命周期。
* *Metrics API.*StorageGRID GMI的底层是开放式API、因为UI是API驱动的。通过这种方法、您可以使用外部监控和分析工具提取数据。




== 从何处查找追加信息

要了解有关本文档中所述信息的更多信息，请查看以下文档和 / 或网站：

* NetApp StorageGRID文档中心 https://docs.netapp.com/us-en/storagegrid-118/[]
* NetApp StorageGRID支持 https://docs.netapp.com/us-en/storagegrid-enable/[]
* NetApp产品文档 https://www.netapp.com/support-and-training/documentation/[]
* 适用于Splunk的NetApp StorageGRID应用程序 https://splunkbase.splunk.com/app/3898/#/details[]

