---
sidebar: sidebar 
permalink: technical-reports/commvault-index.html 
keywords: Backup, on-premises, commvault, storagegrid, object, S3, WORM 
summary: 了解客户和NetApp IT实施的StorageGRID配置的少数用例。 
---
= 使用StorageGRID和Commvault.备份和恢复数据
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Commvault/Commvault/Commvault/Commvault/Commvault/Commvault/Commvault/Commvault/Commvault/Recovery for NetApp软件与NetApp NetApp StorageGRID云存储软件相结合、共同创建了一个联合数据保护解决方案Commvault"完整备份和恢复"和NetApp StorageGRID提供独特且易于使用的解决方案、这些解决方案可以协同工作、帮助您满足全球数据快速增长和法规不断增长的需求。

许多企业希望将存储迁移到云、扩展系统并自动执行长期保留数据的策略。基于云的对象存储因其弹性、扩展能力以及运营和成本效益而闻名、这使其成为备份目标的自然选择。Commvault/Commvault/Commvault/Commvault/Commvault/Commvault/Commvault/Commvault/Commvault/Commvault/Commv NetApp解决方案全球所有类型的客户都采用了Commvault完 整备份和恢复以及StorageGRID组合解决方案。



== 关于Commvault和StorageGRID

Commvault"完整备份和恢复"软件是一款企业级集成数据和信息管理解决方案、在单一平台上从头构建、并具有统一的代码库。它的所有功能都共享后端技术、从而在保护、管理和访问数据方面提供完全集成的方法所带来的无与伦比的优势和优势。该软件包含用于保护、归档、分析、复制和搜索数据的模块。这些模块共享一组通用的后端服务和高级功能、这些服务和功能可以彼此无缝交互。解决方案可解决企业中数据管理的所有方面、同时提供无限可扩展性以及前所未有的数据和信息控制。

NetApp StorageGRID作为Commvault云层 是一种企业级混合云对象存储解决方案。您可以将其部署在多个站点上、无论是专用设备还是软件定义的部署。通过StorageGRID、您可以建立数据管理策略、以确定如何存储和保护数据。StorageGRID会收集您制定和实施策略所需的信息。它分析了广泛的特性和需求、包括性能、持久性、可用性、地理位置、 寿命和成本。随着数据在不同位置之间移动以及数据老化、数据将得到全面维护和保护。

StorageGRID智能策略引擎可帮助您选择以下选项之一：

* 使用纠删编码跨多个站点备份数据、以提高故障恢复能力。
* 将对象复制到远程站点、以最大程度地降低WAN延迟和成本。


当StorageGRID存储对象时、无论该对象位于何处或存在多少副本、您都可以将其作为一个对象进行访问。这种行为对于灾难恢复至关重要、因为借助这种行为、即使数据的一个备份副本损坏、StorageGRID也能够还原数据。

将备份数据保留在主存储中的成本可能很高。使用NetApp StorageGRID时、您可以通过将非活动备份数据迁移到StorageGRID来释放主存储上的空间、同时还可以从StorageGRID的众多功能中受益。备份数据的价值会随着时间的推移而变化、存储成本也会随之变化。StorageGRID可以最大限度地降低主存储的成本、同时提高数据的持久性。



== 主要功能：

CommVault软件平台的主要功能包括：

* 完整的数据保护解决方案、支持虚拟和物理服务器、NAS系统、基于云的基础架构和移动设备上的所有主要操作系统、应用程序和数据库。
* 通过单一控制台简化管理：您可以查看、管理和访问整个企业的所有功能以及所有数据和信息。
* 多种保护方法、包括用于电子发现的数据备份和归档、快照管理、数据复制和内容索引。
* 对磁盘和云存储使用重复数据删除、实现高效存储管理。
* 与NetApp存储阵列(例如AFF、FAS、NetApp HCI和E系列阵列)以及NetApp SolidFire^®^横向扩展存储系统集成。此外，还可以与NetApp Cloud Volumes ONTAP软件集成，在NetApp存储产品组合中自动创建索引化的应用程序感知型NetApp Snapshot™副本。
* 全面的虚拟基础架构管理、可支持领先的内部虚拟虚拟机管理程序和公共云超规模平台。
* 高级安全功能、可限制对关键数据的访问、提供精细管理功能、并为Active Directory用户提供单点登录访问。
* 基于策略的数据管理、支持您根据业务需求(而不是物理位置)管理数据。
* 提供最先进的最终用户体验、让您的用户能够保护、查找和恢复自己的数据。
* API驱动的自动化、支持您使用第三方工具(如vReise Automation或Service Now)来管理数据保护和恢复操作。


有关支持的工作负载的详细信息，请访问 https://www.commvault.com/supported-technologies["CommVault支持的技术"]。



== 备份选项

在云存储上实施CommvaultComplete Backup and Recovery软件时、您有两种备份选项：

* 备份到主磁盘目标、同时将辅助副本备份到云存储。
* 将备份到云存储作为主要目标。


过去、人们认为云或对象存储的性能太低、无法用于主备份。使用主磁盘目标可以加快备份和还原过程、并将辅助副本作为冷备份保留在云上。StorageGRID代表下一代对象存储。StorageGRID的高性能、海量吞吐量以及性能和灵活性远超其他对象存储供应商。

下表列出了StorageGRID中每个备份选项的优势：

[cols="1a,1a,1a"]
|===
|  | 主备份到磁盘和辅助副本到StorageGRID | 主备份到StorageGRID 


 a| 
性能
 a| 
使用实时挂载或实时恢复时恢复速度最快：最适合第0层/第1层工作负载。
 a| 
不能用于实时挂载或实时恢复操作。非常适合流式恢复操作和长期保留。



 a| 
部署架构
 a| 
使用全闪存或旋转磁盘作为第一个备份登录层。StorageGRID用作二级层。
 a| 
使用StorageGRID作为全面的备份目标、简化部署。



 a| 
高级功能(实时还原)
 a| 
supported
 a| 
不支持

|===


== 从何处查找追加信息

要了解有关本文档中所述信息的更多信息，请查看以下文档和 / 或网站：

* StorageGRID 11．11文档中心+https://docs.netapp.com/us-en/storagegrid-119/[]
* NetApp产品文档+
https://docs.netapp.com[]
* CommVault文档+
https://documentation.commvault.com/2024/essential/index.html[]

